### ISSUE TITLE
Some new features

### ISSUE THREAD

**Issue by ShadiestGoat** [OlliePugh/Yet-Another-Grappling-Hook#1]
Heyo! Thanks for the plugin, but i realized that the plugin can be a bit op, and a bit un controllable at times. Would it be possible for you to add 4 options in the config?

Horizantal-Strength:
Vertical-Strength:
Cooldown:
Cooldown-message:

(The cooldown is in ticks, and the cooldown messenger is for when someone tries using the hook before the cooldown timer goes down)
Thanks!

**Comment by OlliePugh** [comment]
Suggestions added to the plugin, 

Althought I did not use ticks, I used seconds instead of ticks.
