### ISSUE TITLE
How to compile into jar?

### ISSUE THREAD

**Issue by ShadiestGoat** [OlliePugh/Yet-Another-Grappling-Hook#2]
Hey sorry this is a slightly noob question, but how do i compile these into a java file?

**Comment by OlliePugh** [comment]
No worries, the curseforge approval system is awfully slow, ill start to add the compiled versions to the releases section on the github, the most recent can be found at: https://github.com/OlliePugh/Yet-Another-Grappling-Hook/releases/tag/v1.02.

Let me know if you have any issues.
